In [1]:
from sklearn import ensemble, model_selection, metrics, datasets

import numpy as np
import pandas as pd

In [2]:
data = datasets.load_digits()

In [3]:
X = data.data

In [4]:
y = data.target

In [5]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.25, shuffle=False)

In [6]:
from scipy.spatial.distance import euclidean
from sklearn.metrics import accuracy_score

In [7]:
predicted = []
# Вычисляем расстояния между x и всеми примерами в обучающей выборке.
for x in X_test:
    distances = (euclidean(x, example) for example in X_train)
# Сортируем все примеры по их расстоянию до x и сохраняем их целевое значение.
    neighbors = sorted(((dist, target) for (dist, target) in zip(distances, y_train)), key=lambda x: x[0])
# Получаем целевые объекты k-nn
    neighbors_targets = [target for (_, target) in neighbors[:1]]
    predicted.append(neighbors_targets)

In [8]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)
err_score = 1 - accuracy_score(y_test, knn.predict(X_test))
print (err_score)

0.0377777777777778


In [9]:
forest = ensemble.RandomForestClassifier(n_estimators=1000)
forest.fit(X_train, y_train)

err_score = 1 - accuracy_score(y_test, forest.predict(X_test))
print (err_score)

0.06444444444444442


In [18]:
knn.predict(X_test)

array([3, 7, 3, 3, 4, 6, 6, 6, 4, 9, 1, 5, 0, 9, 6, 2, 8, 2, 0, 0, 1, 7,
       6, 3, 2, 1, 7, 4, 6, 3, 1, 3, 9, 1, 7, 6, 8, 4, 3, 1, 4, 0, 5, 3,
       6, 9, 6, 1, 7, 5, 4, 4, 7, 2, 8, 2, 2, 5, 7, 9, 5, 4, 8, 8, 4, 9,
       0, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9,
       0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 9, 5, 5, 6, 5, 0, 9, 8, 9, 8, 4,
       1, 7, 7, 3, 5, 1, 0, 0, 2, 2, 7, 8, 2, 0, 1, 2, 6, 3, 3, 7, 3, 3,
       4, 6, 6, 6, 4, 9, 1, 5, 0, 9, 5, 2, 8, 2, 0, 0, 1, 7, 6, 3, 2, 1,
       7, 4, 6, 3, 1, 3, 9, 1, 7, 6, 8, 4, 3, 1, 4, 0, 5, 3, 6, 9, 6, 1,
       7, 5, 4, 4, 7, 2, 8, 2, 2, 5, 7, 9, 5, 4, 8, 8, 4, 9, 0, 9, 9, 8,
       0, 1, 2, 3, 4, 5, 6, 7, 1, 9, 0, 1, 2, 3, 4, 5, 6, 9, 0, 1, 2, 3,
       4, 5, 6, 7, 1, 9, 0, 9, 5, 5, 6, 5, 0, 9, 8, 5, 8, 4, 1, 7, 7, 3,
       5, 1, 0, 0, 2, 2, 7, 8, 2, 0, 1, 2, 6, 3, 3, 7, 7, 8, 4, 6, 6, 6,
       9, 9, 1, 5, 0, 9, 5, 2, 8, 0, 1, 7, 6, 3, 2, 1, 7, 9, 6, 3, 1, 9,
       9, 1, 7, 6, 8, 4, 3, 1, 4, 0, 5, 3, 6, 9, 6,

In [25]:
pred = np.array(predicted)

In [13]:
forest.predict(X_test)

array([3, 7, 3, 3, 4, 6, 6, 6, 4, 9, 1, 5, 0, 9, 6, 2, 8, 2, 0, 0, 1, 7,
       6, 3, 2, 1, 7, 4, 6, 3, 1, 3, 9, 1, 7, 6, 8, 4, 3, 1, 4, 0, 5, 3,
       6, 9, 6, 1, 7, 5, 4, 4, 7, 2, 8, 2, 2, 5, 7, 9, 5, 4, 8, 8, 4, 9,
       0, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9,
       0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 9, 5, 5, 6, 5, 0, 9, 8, 9, 8, 4,
       1, 7, 7, 3, 5, 1, 0, 0, 2, 2, 7, 9, 2, 0, 1, 2, 6, 3, 3, 7, 3, 3,
       4, 6, 6, 6, 4, 9, 9, 5, 0, 9, 5, 2, 8, 2, 0, 0, 9, 7, 6, 3, 2, 1,
       7, 4, 6, 3, 1, 3, 9, 1, 7, 6, 8, 4, 3, 9, 4, 0, 5, 3, 6, 9, 6, 9,
       7, 5, 4, 4, 7, 2, 8, 2, 2, 5, 7, 9, 5, 4, 8, 8, 4, 9, 0, 8, 9, 8,
       0, 1, 2, 3, 4, 5, 6, 7, 1, 9, 0, 1, 2, 3, 4, 5, 6, 9, 0, 1, 2, 3,
       4, 5, 6, 7, 8, 9, 4, 9, 5, 5, 6, 5, 0, 9, 4, 5, 8, 4, 1, 7, 7, 3,
       5, 1, 0, 0, 0, 2, 7, 8, 2, 0, 1, 2, 6, 8, 7, 7, 7, 8, 4, 6, 6, 6,
       7, 9, 1, 5, 0, 9, 5, 2, 8, 0, 1, 7, 6, 3, 2, 1, 7, 7, 6, 3, 1, 3,
       9, 1, 7, 6, 8, 4, 3, 1, 4, 0, 5, 3, 6, 9, 6,

In [30]:
print(pred, sep=',')

[[3]
 [7]
 [3]
 [3]
 [4]
 [6]
 [6]
 [6]
 [4]
 [9]
 [1]
 [5]
 [0]
 [9]
 [6]
 [2]
 [8]
 [2]
 [0]
 [0]
 [1]
 [7]
 [6]
 [3]
 [2]
 [1]
 [7]
 [4]
 [6]
 [3]
 [1]
 [3]
 [9]
 [1]
 [7]
 [6]
 [8]
 [4]
 [3]
 [1]
 [4]
 [0]
 [5]
 [3]
 [6]
 [9]
 [6]
 [1]
 [7]
 [5]
 [4]
 [4]
 [7]
 [2]
 [8]
 [2]
 [2]
 [5]
 [7]
 [9]
 [5]
 [4]
 [8]
 [8]
 [4]
 [9]
 [0]
 [8]
 [0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]
 [0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]
 [0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]
 [0]
 [9]
 [5]
 [5]
 [6]
 [5]
 [0]
 [9]
 [8]
 [9]
 [8]
 [4]
 [1]
 [7]
 [7]
 [3]
 [5]
 [1]
 [0]
 [0]
 [2]
 [2]
 [7]
 [8]
 [2]
 [0]
 [1]
 [2]
 [6]
 [3]
 [3]
 [7]
 [3]
 [3]
 [4]
 [6]
 [6]
 [6]
 [4]
 [9]
 [1]
 [5]
 [0]
 [9]
 [5]
 [2]
 [8]
 [2]
 [0]
 [0]
 [1]
 [7]
 [6]
 [3]
 [2]
 [1]
 [7]
 [4]
 [6]
 [3]
 [1]
 [3]
 [9]
 [1]
 [7]
 [6]
 [8]
 [4]
 [3]
 [1]
 [4]
 [0]
 [5]
 [3]
 [6]
 [9]
 [6]
 [1]
 [7]
 [5]
 [4]
 [4]
 [7]
 [2]
 [8]
 [2]
 [2]
 [5]
 [7]
 [9]
 [5]
 [4]
 [8]
 [8]
 [4]
 [9]
 [0]
 [9]
 [9]
 [8]
 [0]
 [1]


In [31]:
print(predicted, sep='')

[[3], [7], [3], [3], [4], [6], [6], [6], [4], [9], [1], [5], [0], [9], [6], [2], [8], [2], [0], [0], [1], [7], [6], [3], [2], [1], [7], [4], [6], [3], [1], [3], [9], [1], [7], [6], [8], [4], [3], [1], [4], [0], [5], [3], [6], [9], [6], [1], [7], [5], [4], [4], [7], [2], [8], [2], [2], [5], [7], [9], [5], [4], [8], [8], [4], [9], [0], [8], [0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [0], [9], [5], [5], [6], [5], [0], [9], [8], [9], [8], [4], [1], [7], [7], [3], [5], [1], [0], [0], [2], [2], [7], [8], [2], [0], [1], [2], [6], [3], [3], [7], [3], [3], [4], [6], [6], [6], [4], [9], [1], [5], [0], [9], [5], [2], [8], [2], [0], [0], [1], [7], [6], [3], [2], [1], [7], [4], [6], [3], [1], [3], [9], [1], [7], [6], [8], [4], [3], [1], [4], [0], [5], [3], [6], [9], [6], [1], [7], [5], [4], [4], [7], [2], [8], [2], [2], [5], [7], [9], [5], [4], [8], [8], [4], [9], [0], [9], [9], [8], [0], [1],