In [1]:
%pylab inline
from sklearn import ensemble, model_selection, metrics, datasets

import numpy as np
import pandas as pd

Populating the interactive namespace from numpy and matplotlib


In [2]:
data = datasets.load_digits()

In [3]:
X = data.data

In [4]:
y = data.target

In [5]:
X.shape

(1797, 64)

In [6]:
y.shape

(1797,)

In [7]:
rf_classifier = ensemble.RandomForestClassifier()

In [8]:
rf_classifier.fit(X, y)
cv = model_selection.cross_val_score(rf_classifier, X=X, y=y, cv = 10)

In [9]:
cv

array([0.90555556, 0.97777778, 0.93333333, 0.91666667, 0.97222222,
       0.97777778, 0.98888889, 0.97765363, 0.92178771, 0.93854749])

In [10]:
cv.mean()

0.9510211049037863

In [11]:
BC = ensemble.BaggingClassifier(rf_classifier, n_estimators=100).fit(X, y)

In [12]:
cvBC = model_selection.cross_val_score(BC, X=X, y=y, cv = 10)

In [13]:
cvBC

array([0.9       , 0.97222222, 0.95      , 0.92777778, 0.96111111,
       0.96666667, 0.96666667, 0.95530726, 0.91620112, 0.93854749])

In [14]:
cvBC.mean()

0.9454500310366232

In [15]:
BC2 = ensemble.BaggingClassifier(rf_classifier, n_estimators=100, max_features=8).fit(X, y)

In [16]:
cvBC2 = model_selection.cross_val_score(BC2, X=X, y=y, cv = 5)

In [17]:
cvBC2

array([0.93611111, 0.88888889, 0.94150418, 0.96935933, 0.90250696])

In [18]:
cvBC2.mean()

0.9276740947075209